enum MachineActionTypes {
  INCREMENT_BALANCE = 'INCREMENT_BALANCE',
  BUY_PRODUCT = 'BUY_PRODUCT',
  CLEAR_STATUS = 'CLEAR_STATUS',
  WITHDRAW_MONEY = 'WITHDRAW_MONEY',
}

export default MachineActionTypes;
